name: selfie_camera
description: A simple camera plug-in, mainly suitable for selfie scenes, the current function is relatively single
version: 0.0.5
repository: https://github.com/ShareZore/selfie_camera.git
homepage: https://flutter.cn

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  camera: ^0.10.5+6
  image_editor: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  plugin:
    platforms:
      android:
        package: com.example.selfie_camera
        pluginClass: SelfieCameraPlugin
      ios:
        pluginClass: SelfieCameraPlugin